[config]
schemaVersion = "0.0.1"


[package]
namespace = "adamantSpeedrun"
name = "Speedrun_Modpack"
versionNumber = "5.2.0"
description = "Speedrun modpack package."
websiteUrl = "https://github.com/h2pack-speedrun/adamantSpeedrun-Speedrun_Modpack"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.78"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-ModUtil = "4.0.1"
adamant-ModpackLib = "4.2.1"


# -- submodules-start --
adamantSpeedrun-Boonless = "5.0.0"
adamantSpeedrun-Gameplay_QoL = "5.0.0"
adamantSpeedrun-InfiniDD = "5.0.0"
adamantSpeedrun-LiveSplit = "5.0.0"
adamantSpeedrun-QoL = "5.0.0"
adamantSpeedrun-Select_First_Hammer = "5.0.0"
# -- submodules-end --

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = ["mods"]
